### ISSUE TITLE
Questions about compability

### ISSUE THREAD

**Issue by napcat** [LeZuse/node-flatten-deps#1]
Well, I found this problem under windows when I was trying to check my project to TFS.

I was bumping my head to find a solution. I tried this and it just works!!
Thank you so much.

Some questions:
If I install another module after I run flatten-deps, can I run it again to flatten the new module?
Does this work with in all situations, or could it break my project?

**Comment by LeZuse** [comment]
Hi napcat, I am glad you found it useful. When you install a new module after running the script, npm will probably install some modules for the second time (not sure about that). But when you run the script again, it should just optimize the newly installed module.

The script is not heavy tested and there is a lot of space to improve it. For example we use it in our building envinronment, but I would not run it on a client machine yet.
